-- Create portfolios table
create table public.portfolios (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  details text[],
  image text,
  link text,
  tech text[]
);

-- Enable RLS
alter table public.portfolios enable row level security;

-- Create policy to allow public read access
create policy "Allow public read access"
  on public.portfolios
  for select
  to public
  using (true);

-- Insert sample data
insert into public.portfolios (title, description, details, image, link, tech)
values
  (
    'D.Care 건강 검진 센터',
    '대구에 위치한 Dcare 건강검진 센터 랜딩페이지 제작.',
    ARRAY['작업 일정 : 8일', '미팅 및 초안 작업 (1일)', '페이지 작업 (5일)', 'QA 및 수정 (2일)'],
    'https://dcarecenter.kr/images/main-background3.webp',
    'https://dcarecenter.kr',
    ARRAY['React', 'Tailwind Css']
  ),
  (
    '숙원 작가 랜딩페이지 / 리틀리 판매 페이지',
    '서각 작가 숙원님의 랜딩페이지',
    ARRAY['작업일자 (4일)', '미팅 및 초안 작업(1일)', '페이지 작업 (2일)', '리틀리 페이지 세팅작업(1일)'],
    'https://sukone.kr/images/sukone.png',
    'https://sukone.kr',
    ARRAY['React', 'Tailwind Css', 'Littly']
  ),
  (
    'Design LUKA Logo 작업',
    'Design LUKA 의 로고 작업',
    ARRAY['로고 디자인 작업 진행'],
    'https://cdn.litt.ly/images/6GqH1PAmFANy5K4SP4RNVm6rwhLLsX4s?s=600x600&m=outside&f=webp',
    'https://litt.ly/design_luka',
    ARRAY['Littly']
  ),
  (
    'Design LUKA 홈페이지',
    '인테리어 업체 Design LUKA의 홈페이지 제작.',
    ARRAY['관리자 페이지 / 문의사항 자동 분류 자동화 적용'],
    'https://res.cloudinary.com/dti1gtd3u/image/upload/v1751209849/owvpuwmuuiejehkc3kiu.jpg',
    'https://designluka.co.kr/',
    ARRAY['React', 'Tailwind Css']
  );

