-- ════════════════════════════════════════════════════════════════
-- designyeh — gallery portfolios schema + seed
-- Project: stmutjrmoylbmnnxxgfh
-- Run this in the Supabase SQL Editor (DDL needs more than the anon key).
-- Safe to re-run: drops & recreates the table.
-- ════════════════════════════════════════════════════════════════

-- 1. Table ---------------------------------------------------------
drop table if exists public.portfolios cascade;

create table public.portfolios (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default timezone('utc', now()),
  title       text not null,                 -- museum-label title, e.g. "Design LUKA"
  meta        text,                           -- subtitle, e.g. "검진센터 브랜드 랜딩"
  year        text,                           -- display year, e.g. "2024"
  url         text,                           -- full https URL (frame click target)
  image       text,                           -- /works/{slug}.png or remote URL
  tech        text[] default '{}',            -- chips, e.g. {Next.js,Tailwind}
  category    text not null default 'website',-- 'website' | 'logo'
  sort_order  int  not null default 0         -- ascending order on the wall
);

-- 2. Row Level Security: public read only --------------------------
alter table public.portfolios enable row level security;

drop policy if exists "Allow public read access" on public.portfolios;
create policy "Allow public read access"
  on public.portfolios
  for select
  to anon, authenticated
  using (true);

-- 3. Seed: the 6 live sites ----------------------------------------
insert into public.portfolios (title, meta, year, url, image, tech, category, sort_order)
values
  ('Design LUKA',       '인테리어 브랜드 사이트 · 문의 자동 분류',  '2024', 'https://designluka.co.kr', '/works/designluka.png', '{Next.js,Tailwind,Admin}',   'website', 1),
  ('디케어 건강검진센터', '대구 프리미엄 검진센터 브랜드 랜딩',       '2024', 'https://dcarecenter.kr',   '/works/dcare.png',       '{React,Tailwind}',           'website', 2),
  ('MAVS.KR',           '댈러스 매버릭스 팬 커뮤니티 · AI 콘텐츠',   '2025', 'https://mavs.kr',          '/works/mavs.png',        '{Next.js,Supabase,AI}',      'website', 3),
  ('이승선 — Curator',   '큐레이터·도슨트 포트폴리오',               '2025', 'https://sdngazer.art',     '/works/sdngazer.png',    '{Next.js,Supabase}',         'website', 4),
  ('MyBDR',             '농구 토너먼트 · 라이브 기록 플랫폼',         '2025', 'https://mybdr.kr',         '/works/mybdr.png',       '{Next.js,Supabase}',         'website', 5),
  ('HoopNote',          '학원 운영 AI 비서 · SaaS 랜딩',            '2025', 'https://hoopnote.kr',      '/works/hoopnote.png',    '{Next.js,AI}',               'website', 6);

-- ────────────────────────────────────────────────────────────────
-- Adding a new work later = one INSERT. It hangs on the wall
-- automatically (the gallery assigns the next frame slot by order):
--
--   insert into public.portfolios (title, meta, year, url, image, tech, sort_order)
--   values ('New Site', '한 줄 설명', '2026', 'https://example.com',
--           '/works/example.png', '{Next.js}', 7);
-- ────────────────────────────────────────────────────────────────
